### ISSUE TITLE
Add cov_exp_quad() function to the language

### ISSUE THREAD

**Issue by syclik** [stan-dev/stan#1957]
#### Summary:
Expose `cov_exp_quad()` to the language for GPs.

#### Description:
The math function was implemented with stan-dev/math#191. We need to expose it to the language.

#### Todo:
- [ ] `real squared_distance(real x1, real x2)`
    - [x] Add function signature
    - [ ] Add test
- [ ] `real squared_distance(real x1[], real x2[])`
    - [x] Add function signature
    - [ ] Add test
- [ ] `real squared_distance(vector x1, vector x2)`
    - [x] Add function signature
    - [ ] Add test
- [ ] `real squared_distance(row_vector x1, row_vector x2)`
    - [x] Add function signature
    - [ ] Add test
- [ ] `matrix cov_exp_quad(real x[], real sigma, real l)`
    - [x] Add function signature
    - [ ] Add test
- [ ] `matrix cov_exp_quad(vector x[], real sigma, real l)`
    - [x] Add function signature
    - [ ] Add test
- [ ] `matrix cov_exp_quad(row_vector x[], real sigma, real l)`
    - [x] Add function signature
    - [ ] Add test
- [ ] `matrix cov_exp_quad(real x1[], real x2[], real sigma, real l)`
    - [x] Add function signature
    - [ ] Add test
- [ ] `matrix cov_exp_quad(vector x1[], vector x2[], real sigma, real l)`
    - [x] Add function signature
    - [ ] Add test
- [ ] `matrix cov_exp_quad(row_vector x1[], row_vector x2[], real sigma, real l)`
    - [x] Add function signature
    - [ ] Add test

#### Current Version:
v2.10.0

**Comment by bob-carpenter** [comment]
Do we really need all those redundant signatures?  For
the densities, we went with generic vectorization, but that's
not what this is doing, because it's requiring x1 and x2 to
have matching types.  I'd be OK with only using real and vector
(no arrays, no row_vector).

- Bob

**Comment by bob-carpenter** [comment]
Is that squared_distance Euclidean distance?  Should
that be in the name?  Or should we take Euclidean as
the default and only mark the other ones?

- Bob

**Comment by rtrangucci** [comment]
@syclik what is entailed in exposing the functions to the language? I can't remember the steps; are they outlined anywhere?

**Comment by bob-carpenter** [comment]
See:  

https://github.com/stan-dev/stan/wiki/Contributing-New-Functions-to-Stan

And please update it or ask us to if it's incomplete or
confusing.

- Bob

**Comment by bgoodri** [comment]
I'll review it. We need these at least on a branch next week.
