### ISSUE TITLE
Test all math, var, and fvar functions with NaN as input.

### ISSUE THREAD

**Issue by syclik** [stan-dev/stan#236]
We should add additional unit tests to all our math functions with NaN as input variables.

We just caught a bug in `abs()` where an input of NaN was returning 0.
- [x] #843 src/stan/math/functions/ 
- [ ] #844 src/stan/math/matrix/ 
- [x] #845 src/stan/agrad/rev/functions/ 
- [ ] #846 src/stan/agrad/rev/matrix/ 
- [x] #847 src/stan/agrad/fwd/functions/ 
- [ ] #848 src/stan/agrad/fwd/matrix/ 
- [x] #891 src/stan/math/error_handling/
