### ISSUE TITLE
Cleanup test models in this repository

### ISSUE THREAD

**Issue by rok-cesnovar** [stan-dev/stan#3075]
#### Summary:

There are currently 900+ .stan models in this repository that were added here primarily because this is where stanc used to live. That collection of Stan models has gotten pretty stale at this point as we have a newer collection in stanc3 that supersedes this one (at least we think it does). We should remove all the Stan models that are not used in the C++ tests in this repository. 

Steps to close this issue:
- [x] make sure stanc3 collection actually supersedes this one (stan-dev/stanc3#1013)
- [ ] use the stanc3 collection of tests in Integration tests (#3078)
- [ ] remove the unnecessary Stan files (#3079)

#### Current Version:
v2.28.1
