### ISSUE TITLE
test nan input for functions in src/stan/math/functions/

### ISSUE THREAD

**Issue by syclik** [stan-dev/stan#843]
Add tests for nan input.

Functions (as of 8/9/2014):
- [x] #939: Phi.hpp (#850 fixes this behavior)
  - [x] doc
- [x] #944: Phi_approx.hpp: returns NaN
  - [x] doc
- [x] #946: abs.hpp: returns NaN
  - [x] doc
- [x] #1004: as_bool.hpp (#852)
  - [x] doc
- [x] #953: bessel_first_kind.hpp: returns NaN
  - [x] doc
- [x] #954: bessel_second_kind.hpp: returns NaN
  - [x] doc
- [x] binary_log_loss.hpp: returns NaN
  - [x] doc
- [x] binomial_coefficient_log.hpp: returns NaN
  - [x] doc
- [x] #959: digamma.hpp: returns NaN
  - [x] doc
- [x] dist.hpp: returns NaN
- [x] divide.hpp: just int division... currently casts doubles as ints?
- [x] dot.hpp: returns NaN, **doesn't check for mismatched vector sizes**
- [x] dot_self.hpp: returns NaN; **doesn't check for mismatched vector sizes**
- [x] #963: exp2.hpp: returns NaN
  - [x] doc
- [x] #967: falling_factorial.hpp: returns NaN
  - [x] doc
- [x] #972: fdim.hpp (#853)
  - [x] doc
- [x] #973: fma.hpp: returns NaN
  - [x] doc
- [x] #975: gamma_p.hpp: returns NaN
  - [x] doc
- [x] #974: gamma_q.hpp: returns NaN
  - [x] doc
- [x] #1006: ibeta.hpp (#854)
  - [x] doc
- [x] if_else.hpp
  - [x] doc
- [x] int_step.hpp (#856)
  - [x] doc
- [x] #976: inv.hpp: returns NaN
  - [x] doc
- [x] #989: inv_cloglog.hpp: returns NaN
  - [x] doc
- [x] #990: inv_logit.hpp: returns NaN
  - [x] doc
- [x] #978: inv_sqrt.hpp: returns NaN
  - [x] doc
- [x] #977: inv_square.hpp: returns NaN
  - [x] doc
- [x] inverse_softmax.hpp: sets NaN
- [x] is_uninitialized.hpp: **returns false; this is the correct behavior**
  - [x] doc
- [x] lbeta.hpp: returns NaN
  - [x] doc
- [x] #979: lgamma.hpp: returns NaN
  - [x] doc
- [x] #980: lmgamma.hpp: returns NaN
  - [x] doc
- [x] #993: log1m.hpp: returns NaN
  - [x] doc
- [x] #992: log1m_exp.hpp: returns NaN
  - [x] doc
- [x] #991: log1m_inv_logit.hpp: returns NaN
  - [x] doc
- [x] #985: log1p.hpp: returns NaN
  - [x] doc
- [x] #984: log1p_exp.hpp: returns NaN
  - [x] doc
- [x] #983: log2.hpp: returns NaN
  - [x] doc
- [x] #987: log_diff_exp.hpp: returns NaN
  - [x] doc
- [x] log_falling_factorial.hpp: returns NaN
  - [x] doc
- [x] #988: log_inv_logit.hpp: returns NaN
  - [x] doc
- [x] log_rising_factorial.hpp: returns NaN
  - [x] doc
- [x] #986: log_sum_exp.hpp: returns NaN
  - [x] doc
- [x] **logical_and.hpp: returns true for NaN input in either argument**
  - [x] doc
- [x] #1011: **logical_eq.hpp: returns false for NaN input in either argument**
  - [x] doc
- [x] #1008: **logical_gt.hpp: returns false for NaN input in either argument**
  - [x] doc
- [x] #1007: **logical_gte.hpp: returns false for NaN input in either argument**
  - [x] doc
- [x] #1010: **logical_lt.hpp: returns false for NaN input in either argument**
  - [x] doc
- [x] #1009: **logical_lte.hpp: returns false for NaN input in either argument**
  - [x] doc
- [x] **logical_negation.hpp: returns false**
  - [x] doc
- [x] #1012: **logical_neq.hpp: returns true for NaN input in either argument**
  - [x] doc
- [x] **logical_or.hpp: returns true for NaN input in either argument**
  - [x] doc
- [x] logit.hpp: returns NaN
  - [x] doc
- [x] max.hpp: **implementing the standard; if either argument is nan, returns the second argument**; this should be the int version
- [x] min.hpp: **implementing the standard; if either argument is nan, returns the second argument**; this should be the int version
- [x] modified_bessel_first_kind.hpp: returns NaN
  - [x] doc
- [x] modified_bessel_second_kind.hpp: returns NaN
  - [x] doc
- [x] modulus.hpp: no tests necessary: all ints
  - [x] doc
- [x] multiply_log.hpp: returns NaN
  - [x] doc
- [x] owens_t.hpp: returns NaN
  - [x] doc
- [x] #968: rising_factorial.hpp: returns NaN
  - [x] doc
- [x] scaled_add.hpp: sets NaN
- [x] sign.hpp: **returns 1**
  - [x] doc
- [x] #995: square.hpp: returns NaN
  - [x] doc
- [x] **step.hpp; step(NaN) returns 1**
  - [x] doc
- [x] sub.hpp: sets NaN **not safe for vectors of differing sizes**
- [x] sum.hpp: returns NaN **not safe for 0-length vectors**
- [x] trigamma.hpp: returns NaN
  - [x] doc
- [x] value_of.hpp: returns NaN
