### ISSUE TITLE
test nan input for error handling in stan/math/error_handling

### ISSUE THREAD

**Issue by PeterLi2016** [stan-dev/stan#891]
Add tests for nan input.
- [x] #909: check_bounded.hpp
- [x] #910: check_consistent_size.hpp 
- [x] #911: check_consistent_sizes.hpp 
- [x] #912: check_equal.hpp 
- [x] #913: check_finite.hpp 
- [x] #917: check_greater.hpp 
- [x] #914: check_greater_or_equal.hpp  
- [x] #915: check_less.hpp 
- [x] #916: check_less_or_equal.hpp 
- [x] #918: check_nonnegative.hpp 
- [x] check_not_nan.hpp: no new tests needed
- [x] #919: check_positive.hpp 
- [x] #932: check_positive_finite.hpp
- [x] #929: check_cholesky_factor.hpp 
- [x] #935: check_cholesky_factor_corr.hpp: depends on check_unit_vec  
- [x] #920: check_column_index.hpp  
- [x] #906: check_corr_matrix.hpp: fix fabs(y(k,k) - 1.0) > CONSTRAINT_TOLERANCE and depends on check_pos_def
- [x] #936: check_cov_matrix.hpp: depends on check_pos_def and check_sym 
- [x] #930: check_ldlt_factor.hpp: only fails if nan is in lower triangular portion of matrix  
- [x] #928: check_lower_triangular.hpp 
- [x] #921: check_matching_dims.hpp  
- [x] #922: check_matching_sizes.hpp 
- [x] #923: check_multiplicable.hpp 
- [x] #924: check_nonzero_size.hpp 
- [x] #933: check_ordered.hpp 
- [x] #901: check_pos_definite.hpp 
- [x] #908: check_pos_semidefinite.hpp 
- [x] #931: check_positive_ordered.hpp  
- [x] check_range.hpp: no test needs to be added since it takes args size_t
- [x] #925: check_row_index.hpp 
- [x] #897: check_simplex.hpp
- [x] check_size_match.hpp: no test needs to be added since it takes args size_t
- [x] #937: check_spsd_matrix.hpp: depends on check_sym and check_pos_semidef 
- [x] #934: check_square.hpp 
- [x] #926: check_std_vector_index.hpp  
- [x] #905: check_symmetric.hpp: fix fabs(y(m,n) - y(n,m)) > CONSTRAINT_TOLERANCE but should this return true if the matrix is 1x1 with element (0,0) being nan? what if it's a 2x2 and symmetric in that (0,1)=(1,0)=nan?
- [x] #899: check_unit_vector.hpp 
- [x] #927: check_vector.hpp 
- [x] constraint_tolerance.hpp: no test needed
- [x] validate_non_negative_index.hpp: no test needs to be added since it takes arg int

After all of the above pull requests have been merged, check the branch https://github.com/stan-dev/stan/tree/feature/issue-891-error-checks-nan and make sure everything here was merged in -- the doc was partially redone since a lot of it was done all in one commit.
- [x] delete this branch when done
